## Импорт библиотек

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Загрузка данных

In [6]:
df = pd.read_csv('climat_official.csv', parse_dates=['date'])
era5 = pd.read_csv('ERA5_full.csv', parse_dates=['date'])

In [7]:
df.head()

,Индекс ВМО,date,Средняя температура воздуха,Количество осадков,Горизонтальная дальность видимости,Общее количество облачности,Количество облачности нижнего яруса,Форма облаков верхнего яруса,Форма облаков среднего яруса,Форма облаков вертикального развития,...,Сумма осадков_missing,Температура поверхности почвы_missing,Парциальное давление водяного пара_missing,Относительная влажность воздуха_missing,Дефицит насыщения водяного пара_missing,Атмосферное давление на уровне станции_missing,Атмосферное давление на уровне моря_missing,Характеристика барической тенденции_missing,Величина барической тенденции_missing,num_missing
0,34059,1981-01-01,0.1,0.4,55.25,10.00,10.000,8.00,8.000,0.00,...,0,0,0,0,0,0,0,0,0,0
1,34152,1981-01-01,-0.1,0.4,71.00,10.00,7.500,8.00,7.000,0.00,...,0,0,0,0,0,0,0,0,0,0
2,34163,1981-01-01,-1.0,0.4,80.00,10.00,7.500,8.00,6.250,0.00,...,0,0,0,0,0,0,0,0,0,0
3,34172,1981-01-01,0.4,0.0,70.00,10.00,8.750,8.00,7.250,0.00,...,0,0,0,0,0,0,0,0,0,0
4,34186,1981-01-01,-3.6,1.0,24.50,9.75,8.625,6.25,6.375,2.25,...,0,0,0,0,0,0,0,0,0,0

In [9]:
era5.head()

,Индекс ВМО,date,latitude,longitude,2m_dewpoint_temperature_stream-oper_daily-mean,2m_temperature_0_daily-mean,surface_pressure_0_daily-mean,total_precipitation_0_daily-mean,maximum_2m_temperature_since_previous_post_processing_0_daily-mean,skin_temperature_0_daily-mean,mean_evaporation_rate_0_daily-mean,clear_sky_direct_solar_radiation_at_surface_0_daily-mean,evaporation_0_daily-mean,potential_evaporation_0_daily-mean,convective_precipitation_0_daily-mean,avg_pevr,avg_cpr,total_precipitation_scaled
0,34059,1940-01-01,52.0,43.65,-17.98183,-15.66160,99108.64,0.006866,-15.46342,-15.76063,-6.382252e-08,143130.860,-0.000235,-0.022892,0.0,-0.006360,0.0,-0.059208
1,34059,1940-01-02,52.0,43.65,-25.21587,-22.83079,99859.69,0.000119,-22.02915,-24.17704,2.240773e-07,114577.516,0.000809,-0.005217,0.0,-0.001451,0.0,-0.231404
2,34059,1940-01-03,52.0,43.65,-28.55027,-26.00974,99506.39,0.003672,-25.81016,-27.42121,2.444089e-07,112423.450,0.000887,-0.008524,0.0,-0.002368,0.0,-0.140737
3,34059,1940-01-04,52.0,43.65,-23.95266,-21.39904,99039.92,0.145149,-21.49006,-21.82960,3.162277e-07,105748.640,0.001139,-0.017972,0.0,-0.004992,0.0,3.470007
4,34059,1940-01-05,52.0,43.65,-15.92990,-14.26237,98507.39,0.070214,-14.27793,-15.25153,1.394192e-06,113422.200,0.005017,-0.022017,0.0,-0.006115,0.0,1.557536

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112035 entries, 0 to 112034
Data columns (total 51 columns):
 #   Column                                           Non-Null Count   Dtype
---  ------                                           --------------   -----
 0   Индекс ВМО                                       112035 non-null  int64
 1   date                                             112035 non-null  datetime64[ns]
 2   Средняя температура воздуха                      112035 non-null  float64
 3   Количество осадков                               112035 non-null  float64
 4   Горизонтальная дальность видимости               112035 non-null  float64
 5   Общее количество облачности                      112035 non-null  float64
 6   Количество облачности нижнего яруса              112035 non-null  float64
 7   Форма облаков верхнего яруса                     112035 non-null  float64
 8   Форма облаков среднего яруса                     112035 non-null  float64
 9   Форма облаков вертикального развития             112035 non-null  float64
 10  Слоистые и слоисто-кучевые облака                112035 non-null  float64
 11  Слоисто-дожд,разорванно-дождевые облака          112035 non-null  float64
 12  Высота нижней границы облачности                 110929 non-null  float64
 13  Погода между сроками                             112035 non-null  float64
 14  Погода в срок наблюдения                         112035 non-null  float64
 15  Направление ветра                                112035 non-null  float64
 16  Средняя скорость ветра                           112035 non-null  float64
 17  Максимальная скорость ветра                      112035 non-null  float64
 18  Сумма осадков                                    112035 non-null  float64
 19  Температура поверхности почвы                    112035 non-null  float64
 20  Парциальное давление водяного пара               112035 non-null  float64
 21  Относительная влажность воздуха                  112035 non-null  float64
 22  Дефицит насыщения водяного пара                  112035 non-null  float64
 23  Атмосферное давление на уровне станции           112035 non-null  float64
 24  Атмосферное давление на уровне моря              112035 non-null  float64
 25  Характеристика барической тенденции              112035 non-null  float64
 26  Величина барической тенденции                    112035 non-null  float64
 27  Горизонтальная дальность видимости_missing       112035 non-null  int64
 28  Общее количество облачности_missing              112035 non-null  int64
 29  Количество облачности нижнего яруса_missing      112035 non-null  int64
 30  Форма облаков верхнего яруса_missing             112035 non-null  int64
 31  Форма облаков среднего яруса_missing             112035 non-null  int64
 32  Форма облаков вертикального развития_missing     112035 non-null  int64
 33  Слоистые и слоисто-кучевые облака_missing        112035 non-null  int64
 34  Слоисто-дожд,разорванно-дождевые облака_missing  112035 non-null  int64
 35  Высота нижней границы облачности_missing         112035 non-null  int64
 36  Погода между сроками_missing                     112035 non-null  int64
 37  Погода в срок наблюдения_missing                 112035 non-null  int64
 38  Направление ветра_missing                        112035 non-null  int64
 39  Средняя скорость ветра_missing                   112035 non-null  int64
 40  Максимальная скорость ветра_missing              112035 non-null  int64
 41  Сумма осадков_missing                            112035 non-null  int64
 42  Температура поверхности почвы_missing            112035 non-null  int64
 43  Парциальное давление водяного пара_missing       112035 non-null  int64
 44  Относительная влажность воздуха_missing          112035 non-null  int64
 45  Дефицит насыщения водяного пара_missing          112035 non-null  int64
 46  Атмосферное давление на уровне станции_missing   112035 non-null  int64
 47  Атмосферное давление на уровне моря_missing      112035 non-null  int64
 48  Характеристика барической тенденции_missing      112035 non-null  int64
 49  Величина барической тенденции_missing            112035 non-null  int64
 50  num_missing                                      112035 non-null  int64
dtypes: datetime64[ns](1), float64(25), int64(25)
memory usage: 43.6 MB

## Добавление лагов

### Сортировка

## Удаления пропусков

## Конструирование признаков